repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.22
    hooks:
      - id: ruff
        args: [--fix]

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy src
        language: python
        types: [python]
        pass_filenames: false
